/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsyxue_jnidemo_natives_JNI */

#ifndef _Included_com_tsyxue_jnidemo_natives_JNI
#define _Included_com_tsyxue_jnidemo_natives_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tsyxue_jnidemo_natives_JNI
 * Method:    HelloC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tsyxue_jnidemo_natives_JNI_HelloC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
