/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsyxue_jnidemo_natives_CcallJava */

#ifndef _Included_com_tsyxue_jnidemo_natives_CcallJava
#define _Included_com_tsyxue_jnidemo_natives_CcallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tsyxue_jnidemo_natives_CcallJava
 * Method:    callbackString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tsyxue_jnidemo_natives_CcallJava_callbackString
  (JNIEnv *, jobject);

/*
 * Class:     com_tsyxue_jnidemo_natives_CcallJava
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tsyxue_jnidemo_natives_CcallJava_callbackAdd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
